id = "um-ami_ruins"
name = "Um'Ami ruins"
minHeight = 36
[mapCenter]
x = 25.5
y = 51
z = -137.5
yaw = 90
pitch = 90

[team1Config]
[[team1Config.spawnPos]]
x = 44.5
y = 51
z = -87.5
yaw = 180
pitch = 0
[[team1Config.spawnPos]]
x = 42.5
y = 51
z = -86.5
yaw = 180
pitch = 0
[[team1Config.spawnPos]]
x = 40.5
y = 51
z = -86.5
yaw = 180
pitch = 0
[[team1Config.spawnPos]]
x = 38.5
y = 51
z = -87.5
yaw = 180
pitch = 0
[team1Config.spawnViewPos]
x = 41.5
y = 53
z = -91.5
yaw = 0
pitch = 30

[team2Config]
[[team2Config.spawnPos]]
x = 44.5
y = 51
z = -87.5
yaw = 180
pitch = 0
[team2Config.spawnViewPos]
x = 9.5
y = 53
z = -183.5
yaw = 180
pitch = 30

[cutscene]
[cutscene.start]
x = 25.5
y = 46
z = -137.5
yaw = 90
pitch = 90
[cutscene.end]
x = 50.5
y = 73
z = -96.5
yaw = 148.7
pitch = 32.6
